<a href="https://colab.research.google.com/github/NahidurRahaman/Numpy/blob/main/Numpy_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from time import process_time


In [39]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.00015167600000021153


In [4]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)


0.000984137000000107


Numpy Array

In [5]:
# List
list1 = [1,2,3,4,5,6]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6]


list

In [6]:
np_array = np.array(list1)
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

In [7]:
#creating a 1 dim array
a = np.array([1,2,3,4,5,6])
print(a)


[1 2 3 4 5 6]


In [8]:
a.shape

(6,)

In [9]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.shape

(2, 3)

In [11]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Initial Placehoder in numpy arays

In [12]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create a numpy array of ones
y = np.ones((3,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
#array of paticular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity martix
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create numpy array with random values
c = np.random.random((3,4))

print(c)

[[0.66925262 0.58429534 0.35485328 0.68814335]
 [0.9133683  0.8254608  0.71612602 0.46849622]
 [0.68526134 0.66894027 0.00802563 0.74443999]]


In [17]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[22 32 32 85 49]
 [60 50 56 78 55]
 [97 51 39 21 92]]


In [18]:
# array of evenly spaced values --> specifying the number of vlues required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[49 14 71 31 46]
 [44 14 24 60 12]
 [86 61 47 36 18]
 [67 89 85 83 34]
 [33 79 42 50 57]]


In [22]:
#array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimensions
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)


int64


Mathmatical operation on a np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[3 9 3]
 [8 8 9]
 [6 0 4]]
[[19 18 18]
 [14 18 19]
 [16 14 11]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 27 21]
 [22 26 28]
 [22 14 15]]
[[-16  -9 -15]
 [ -6 -10 -10]
 [-10 -14  -7]]
[[ 57 162  54]
 [112 144 171]
 [ 96   0  44]]
[[0.15789474 0.5        0.16666667]
 [0.57142857 0.44444444 0.47368421]
 [0.375      0.         0.36363636]]


In [30]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [31]:
print(a)
print(b)

[[6 7 1]
 [8 6 4]
 [7 7 7]]
[[13 11 17]
 [13 17 15]
 [13 13 19]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 18 18]
 [21 23 19]
 [20 20 26]]
[[ -7  -4 -16]
 [ -5 -11 -11]
 [ -6  -6 -12]]
[[ 78  77  17]
 [104 102  60]
 [ 91  91 133]]
[[0.46153846 0.63636364 0.05882353]
 [0.61538462 0.35294118 0.26666667]
 [0.53846154 0.53846154 0.36842105]]


Array Mainpulation

In [33]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 7 0]
 [5 9 7]]
(2, 3)


In [34]:
# transpos
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 5]
 [7 9]
 [0 7]]
(3, 2)


In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 6 1]
 [2 4 0]]
(2, 3)


In [36]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 2]
 [6 4]
 [1 0]]
(3, 2)


In [37]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 0]
 [7 5 4]]
(2, 3)


In [38]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [0 7]
 [5 4]]
(3, 2)
