<a href="https://colab.research.google.com/github/NahidurRahaman/Numpy/blob/main/Numpy_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

In [3]:
nums = [1, 2, 3, 4, 5]
my_np_array = np.array(nums)
print(my_np_array)
print(type(my_np_array))
print(my_np_array.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
print(my_np_array.ndim)
print(my_np_array.size)

1
5


In [5]:
x = 5
x
my_np_array.dtype

dtype('int64')

In [6]:
zero_np_array = np.zeros((3, 4))
print(zero_np_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
one_np_array = np.ones((3, 4))
print(one_np_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
                              #shape   val
specific_num_np_array = np.full((3, 4), 5)
print(specific_num_np_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [9]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
empty_np_array = np.empty((3, 4)) # array of uninitialized values
empty_np_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
print(empty_np_array.dtype)

float64


In [12]:
# Type casting
empty_np_array = empty_np_array.astype(int)
print(empty_np_array.dtype)

int64


In [13]:
empty_np_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
# Sequencial array
              # start, stop before, step(default 1)
my_arr = np.arange(1,   10)
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_arr2 = np.arange(1, 11, 2)
my_arr2

array([1, 3, 5, 7, 9])

In [16]:
# Linearly spaced array
# Example = 0, 2.5, 5, 7.5, 10 #space = 2.5

my_arr3 = np.linspace(0, 10, 5)
my_arr3

array([ 0. ,  2.5,  5. ,  7.5, 10. ])